'use strict';

// Decides when a LOCAL server must run `npm install`. Used by BOTH the release updater
// (services/updater.service.js) and the local-server supervisor (LOCAL_SERVER_SUPERVISOR.js,
// generated by release-package.service.js). They write the same marker file
// (node_modules/.jms-backend-deps.sha256), so they must compute the same value — when
// they didn't, each saw the other's marker as "changed" and ran npm install on every boot.
//
// Only what decides which packages get installed is hashed. The app version in
// package.json / package-lock.json changes with every release; hashing the raw files
// made every version bump look like a dependency change (npm install, lockfile rewrite,
// extra restart per release).

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function dependencyContent(fileName, raw) {
  try {
    const json = JSON.parse(raw);
    if (fileName === 'package.json') {
      return JSON.stringify({
        dependencies: json.dependencies || {},
        optionalDependencies: json.optionalDependencies || {},
        peerDependencies: json.peerDependencies || {},
        // npm uses root overrides to pick transitive versions.
        overrides: json.overrides || {}
      });
    }
    const lock = Object.assign({}, json);
    delete lock.version;
    delete lock.name;
    if (lock.packages && lock.packages['']) {
      lock.packages = Object.assign({}, lock.packages, { '': Object.assign({}, lock.packages['']) });
      delete lock.packages[''].version;
      delete lock.packages[''].name;
    }
    return JSON.stringify(lock);
  } catch (_e) {
    return raw.toString('utf8'); // unreadable JSON: fall back to the raw bytes
  }
}

function getDependencySignature(rootDir) {
  const hash = crypto.createHash('sha256');
  for (const fileName of ['package.json', 'package-lock.json']) {
    const filePath = path.join(rootDir, fileName);
    if (fs.existsSync(filePath)) {
      hash.update(fileName);
      hash.update(dependencyContent(fileName, fs.readFileSync(filePath)));
    }
  }
  return hash.digest('hex');
}

module.exports = { getDependencySignature, dependencyContent };
